"""empty message

Revision ID: 3540f794424d
Revises: 7e5face76e71
Create Date: 2024-06-05 12:01:03.293918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3540f794424d'
down_revision = '7e5face76e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('sold')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
