"""empty message

Revision ID: 7e5face76e71
Revises: 7370414178b2
Create Date: 2024-06-05 07:51:31.952150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5face76e71'
down_revision = '7370414178b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('uq_item_contact', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_item_contact', ['contact'])
        batch_op.drop_column('sold')

    # ### end Alembic commands ###
